include(${CMAKE_CURRENT_LIST_DIR}/CompilerWarnings.cmake)
set_project_warnings()

if (CMAKE_BUILD_TYPE MATCHES Debug)
    include(${CMAKE_CURRENT_LIST_DIR}/Sanitizers.cmake)
    set(ENABLE_SANITIZER_ADDRESS YES)
    if (NOT APPLE)
        set(ENABLE_SANITIZER_LEAK YES)
    endif()
    set(ENABLE_SANITIZER_UNDEFINED_BEHAVIOR YES)
    enable_sanitizers()
endif ()